# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_textt',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_textt',
            new_name='question_text',
        ),
    ]
